### PR TITLE
Removed unncessary modification to the window object qApp function

### PR DESCRIPTION
**Pull request by humean**
This PR removed the unnecessary modification to the window object to store a reference to the qlik object. Instead, the qlik object is stored within the module scope, and so doesn't pollute global scope.

### CODE REVIEW

**Comment by yianni-ververis** [comment]
I think I did that because when we try to connect to more than one app, the injection is happening twice and then we get errors.

Can you try and see if this example works with your changes?
https://webapps.qlik.com/qdt-components/react/index.html#/embed-object-multi-app

**Comment by humean** [comment]
Ok, so you need to model your loadCapabilityApis API to return the same Promise every time. I'll make another change. Modifying the global object isn't necessary to supporting multiple app instances. 

I created this PR because a colleague using the lib is going to face challenges by testers and security if any application internals are exposed in the global scope.

**Comment by humean** [comment]
Does that address your concerns?

**Comment by humean** [comment]
Another option is to have the QdtComponents constructor have an optional param that opt-outs of the Capability Apis injection.

**Comment by ashishpadman** [comment]
Hi, I use QdtComponents at a large financial firm and having the qlik app on the window scope means we cannot pass through security vulnerability scanning/testing. We are sticking to an earlier version of QdtComponents (1.1.52) because of this. Accepting this request would allow us to work with the latest version

**Pull request merged**
